# Generated by Django 5.2.4 on 2025-08-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='area_interes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
