# Generated by Django 5.2.3 on 2025-08-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='ciudad',
            new_name='provincia',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='edad',
        ),
        migrations.AddField(
            model_name='descripcion',
            name='usuario',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(default='ApellidoPorDefecto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
