# Generated by Django 5.2.5 on 2025-09-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_ciudad_club_provincia_remove_jugador_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='escudo',
            field=models.ImageField(blank=True, null=True, upload_to='clubes/'),
        ),
    ]
