# Generated by Django 5.2.3 on 2025-08-13 03:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panopolis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='fecha_realizacion',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Autor (Personal de laboratorio)'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 8, 13, 3, 41, 17, 355378, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='informes_imagenes/', verbose_name='Imagen/Archivo adjunto'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='panopolis.paciente'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='subtitulo',
            field=models.CharField(default='', max_length=255, verbose_name='Subtítulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='cuerpo',
            field=models.TextField(verbose_name='Cuerpo del Informe'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='panopolis.estudio'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título del Informe'),
        ),
    ]
